<?php

namespace pitaks\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisteredReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisteredReservationRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBulder()
    {
        return $this->createQueryBuilder("r");
    }
    /**
     * @param string $date
     * @return array
     */
    public function findOlderThenData($date){
        $r = $this->getQueryBulder()
            ->select()
            ->where('r.reservationEnd < :date')
            ->setParameter('date', $date)
            ->getQuery()->getResult();
        return $r;
    }

    /**finds new Reservations from data
     */
    /**
     * @param string $username
     * @param string $date
     * @return int
     */
    public function findUserLastReservationFromData($username, $date)
    {
        $r = $this->getQueryBulder()
            ->select()
            ->where('r.reservationEnd >:date')
            ->andWhere('r.friendId=:username')
            ->andWhere('r.isConfirmed=false')
            ->setParameter('date', $date)
            ->setParameter('username', $username)
            ->getQuery()->getResult();
        return count($r);
    }

    /**
     * @param $username
     * @param $date
     * @return array
     */
    public function findAllUserUpcomingReservations($username,$date)
    {
        $r = $this->getQueryBulder()
            ->select()
            ->where('r.reservationStart >:date')
            ->andWhere('r.friendId=:username')
            ->orWhere('r.userId=:username')
            ->andWhere('r.isConfirmed=true')
            ->setParameter('date', $date)
            ->setParameter('username', $username)
            ->getQuery()->getResult();
        return $r;
    }
}
