<?php

namespace pitaks\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    /**
     * @param $tableId
     * @return array
     */
 public function findByTableReservationData($tableId)
 {
     $qb = $this->createQueryBuilder('r');
     $r=$qb->select('r')->where('r.tableId='.$tableId)->getQuery()->getResult();
     return $r;

 }

    /**
     * @param $tableId
     * @param $date
     * @return array
     */
    public function findByDate($tableId, $date)
    {
        $qb = $this->createQueryBuilder('r');
        $r=
        $qb->select('r')->
        where(
            $qb->expr()->like('r.reservationStart', ':date'),
            ('r.tableId='.$tableId)
        )
            ->setParameter('date','%'.$date.'%')
            ->getQuery()
            ->getResult();
        return $r;
    }

    /**
     * @param $tableId
     * @param $date
     * @return array
     */
    public function findFreeDateReservations($tableId, $date)
    {
        $qb = $this->createQueryBuilder('r');
        $r=
            $qb->select('r')->
            where(
                $qb->expr()->like('r.reservationStart', ':date'),
                ('r.tableId='.$tableId),
                ('r.isFree=true')
            )
               ->setParameter('date','%'.$date.'%')
                ->getQuery()
                ->getResult();
        return $r;
    }

}
