<?php

namespace pitaks\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{

 public function findByTableReservationData($tableId)
 {
     $qb = $this->createQueryBuilder('r');
     $r=$qb->select('r')->where('r.tableId='.$tableId)->getQuery()->getResult();
     return $r;

 }
    public function findByDate($tableId, $date)
    {
        $qb = $this->createQueryBuilder('r');
        $r=
        $qb->select('r')->
        where(
            $qb->expr()->like('r.reservationStart', ':date'),
            ('r.tableId='.$tableId)
        )
            ->setParameter('date','%'.$date.'%')
            ->getQuery()
            ->getResult();
//  where->getQuery()->getResult();
        return $r;
    }
}
