<?php

namespace pitaks\KickerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablesRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBulder()
    {
        return $this->createQueryBuilder("t");
    }

    /**
     * @param array $criteria
     * @param array $orderBy
     * @param null $limit
     * @param null $offset
     * @return array
     */
    public function getTableList(array $criteria = [], array $orderBy = null, $limit = null, $offset = null)
    {
        if (empty($criteria)) {
            return $this->findAll();
        }

        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * @param Table $table
     */
    public function save(Table $table)
    {
        $em = $this->getEntityManager();
        $em->persist($table);
        $em->flush();
    }


}
