<?php

namespace pitaks\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LastReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastReviewsRepository extends EntityRepository
{
}
