pitaks_kicker_homepage:
    path:     /
    defaults: { _controller: pitaksKickerBundle:Default:index }

index:
    path:     /hello/{name}
    defaults: { _controller: pitaksKickerBundle:Profile:index }

edit:
    path:     /edit
    defaults: { _controller: pitaksKickerBundle:Profile:edit }

createTable:
    path:     /createTable
    defaults: { _controller: pitaksKickerBundle:Table:new }

editTable:
    path:     /editTable/{id}
    defaults: { _controller: pitaksKickerBundle:Table:editTable }

daleteTable:
        path:     /deleteTable/{id}
        defaults: { _controller: pitaksKickerBundle:Table:delete }