pitaks_kicker_homepage:
    path:     /
    defaults: { _controller: pitaksKickerBundle:Default:index }

createTable:
    path:     admin/table/createTable
    defaults: { _controller: pitaksKickerBundle:Table:new }

editTable:
    path:     admin/table/editTable/{id}
    defaults: { _controller: pitaksKickerBundle:Table:editTable }

daleteTable:
        path:  admin/table/deleteTable/{id}
        defaults: { _controller: pitaksKickerBundle:Table:delete }
tableList:
      path: admin/table/list
      defaults: { _controller: pitaksKickerBundle:Table:index }

new_reservation:
    path:     admin/table/{tableId}/newReservation
    defaults: { _controller: pitaksKickerBundle:Reservation:newReservation }

delete_reservation:
    path:     admin/table/{tableId}/deleteReservation/{id}
    defaults: { _controller: pitaksKickerBundle:Reservation:deleteReservation }

edit_reservation:
    path:     admin/table/{tableId}/editReservation/{id}
    defaults: { _controller: pitaksKickerBundle:Reservation:editReservation }

reservationList:
  path:  admin/table/{tableId}/reservations
  defaults: { _controller: pitaksKickerBundle:Reservation:reservationList }

viewRes:
    path:  view
    defaults: { _controller: pitaksKickerBundle:Reservation:view }
    options:
                        expose: true
ajaxj:
    path:  ajax
    defaults: { _controller: pitaksKickerBundle:Reservation:ajax }
show:
    path: rez
    defaults: {_controller: pitaksKickerBundle:Table:ShowResult }
timelist:
    path: timeList
    defaults: {_controller: pitaksKickerBundle:Reservation:timeList}
    options:
           expose: true
saveReservation:
    path: save
    defaults: {_controller: pitaksKickerBundle:Reservation:saveReservation}
    options:
           expose: true
isTableFree:
    path: isTableFree/{tableId}
    defaults: {_controller: pitaksKickerBundle:Reservation:isTableFree}
#table rating
saveTableRate:
    path: /table/{tableId}/saveRating
    defaults: {_controller: pitaksKickerBundle:Table:saveTableRate}
    options:
           expose: true
tableRateModal:
    path: /table/RateModal
    defaults: {_controller: pitaksKickerBundle:Table:rateTableView}

#comment
tableComment:
    path: /table/{tableId}/newComment
    defaults: {_controller: pitaksKickerBundle:Comment:newComment}

#TableREzultatas
tableResult:
    path: /table/{tableId}/result
    defaults: {_controller: pitaksKickerBundle:Table:showTableResults}

tableEveryDayReservations:
    path: /table/{tableId}/reservationSelector
    defaults: {_controller: pitaksKickerBundle:Reservation:showReservationViewSelector}
    options:
           expose: true
tableEveryDayReservationsList:
    path: /table/{tableId}/everyDayReservationsList
    defaults: {_controller: pitaksKickerBundle:Reservation:everyDayReservationsList}
    options:
            expose: true
