pitaks_kicker_homepage:
    path:     /
    defaults: { _controller: pitaksKickerBundle:Default:index }

createTable:
    path:     table/createTable
    defaults: { _controller: pitaksKickerBundle:Table:new }

editTable:
    path:     table/editTable/{id}
    defaults: { _controller: pitaksKickerBundle:Table:editTable }

daleteTable:
        path:  table/deleteTable/{id}
        defaults: { _controller: pitaksKickerBundle:Table:delete }
tableList:
      path: /table/list
      defaults: { _controller: pitaksKickerBundle:Table:index }

new_reservation:
    path:     table/{tableId}/newReservation
    defaults: { _controller: pitaksKickerBundle:Reservation:newReservation }

delete_reservation:
    path:     table/{tableId}/deleteReservation/{id}
    defaults: { _controller: pitaksKickerBundle:Reservation:deleteReservation }

edit_reservation:
    path:     table/{tableId}/editReservation/{id}
    defaults: { _controller: pitaksKickerBundle:Reservation:editReservation }

reservationList:
  path:  table/{tableId}/reservations
  defaults: { _controller: pitaksKickerBundle:Reservation:reservationList }

viewRes:
    path:  view
    defaults: { _controller: pitaksKickerBundle:Reservation:view }
ajaxj:
    path:  ajax
    defaults: { _controller: pitaksKickerBundle:Reservation:ajax }
show:
    path: rez
    defaults: {_controller: pitaksKickerBundle:Table:ShowResult }
timelist:
    path: timeList
    defaults: {_controller: pitaksKickerBundle:Reservation:timeList}
saveReservation:
    path: save
    defaults: {_controller: pitaksKickerBundle:Reservation:saveReservation}
isTableFree:
    path: isTableFree/{tableId}
    defaults: {_controller: pitaksKickerBundle:Reservation:isTableFree}

example:
    path: example
    defaults: {_controller: pitaksKickerBundle:Profile:index}