pitaks_kicker_homepage:
    path:     /
    defaults: { _controller: pitaksKickerBundle:Default:index }

index:
    path:     /hello/{name}
    defaults: { _controller: pitaksKickerBundle:Profile:index }

edit:
    path:     /edit
    defaults: { _controller: pitaksKickerBundle:Profile:edit }

createTable:
    path:     table/createTable
    defaults: { _controller: pitaksKickerBundle:Table:new }

editTable:
    path:     table/editTable/{id}
    defaults: { _controller: pitaksKickerBundle:Table:editTable }

daleteTable:
        path:  table/deleteTable/{id}
        defaults: { _controller: pitaksKickerBundle:Table:delete }
tableList:
      path: /table/list
      defaults: { _controller: pitaksKickerBundle:Table:index }