services:
  api_data:
   class: pitaks\KickerBundle\Services\APIDataService
   arguments: ["@doctrine.orm.entity_manager"]
   calls:
           - [setContainer, ['@service_container']]
  api_success_listener:
      class: pitaks\KickerBundle\EventListener\ApiSuccessListener
      calls:
          - [setLogger, ['@logger']]
      tags:
          - { name: kernel.event_listener, event: api_success, method: onApiSuccess }
  api_error_listener:
      class: pitaks\KickerBundle\EventListener\ApiErrorListener
      calls:
            - [setLogger, ['@logger']]
      tags:
         - { name: kernel.event_listener, event: api_failed, method: onApiError }
  api_query_listener:
      class: pitaks\KickerBundle\EventListener\ApiQueryListener
      tags:
          - { name: kernel.event_listener, event: api_query, method: onChange }
  reservation_service:
     class: pitaks\KickerBundle\Services\ReservationService
     arguments: ["@doctrine.orm.entity_manager"]
     calls:
             - [setContainer, ['@service_container']]
  rank_service:
       class: pitaks\UserBundle\Services\RankService
       arguments: ["@doctrine.orm.entity_manager"]
       calls:
               - [setContainer, ['@service_container']]