services:
  api_data:
   class: pitaks\KickerBundle\Services\APIDataService
   arguments: ["@doctrine.orm.entity_manager"]
#    pitaks_kicker.example:
#        class: pitaks\KickerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
