services:
  api_data:
   class: pitaks\KickerBundle\Services\APIDataService
   arguments: ["@doctrine.orm.entity_manager"]

  api_listener:
    class: pitaks\KickerBundle\EventListener\ApiEventListener
    tags:
        - { name: kernel.event_listener, event: api_success, method: onApiSuccess }
        - { name: kernel.event_listener, event: api_failed, method: onApiError }
