<?php

namespace pitaks\RSSFeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedProviderRepository extends EntityRepository
{
}
