<?php

namespace pitaks\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamStatisticRepository extends EntityRepository
{
}
