<?php

namespace pitaks\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamReservationRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBulder()
    {
        return $this->createQueryBuilder("t");
    }

    public function getConfirmedReservations($teamId)
    {
       $query = $this->getQueryBulder()->
            select()->
            where('t.competitorTeam='.$teamId)->
            orWhere('t.team='.$teamId)->
            andWhere('t.isConfirmed=true')->
            getQuery();
        return $query->getResult();
    }

    /**
     * @param string $date
     * @return array
     */
    public function findOlderThenData($date){
        $r = $this->getQueryBulder()
            ->select()
            ->where('t.reservationEnd < :date')
            ->setParameter('date', $date)
            ->getQuery()->getResult();
        return $r;
    }
}
