<?php

namespace pitaks\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBulder()
    {
        return $this->createQueryBuilder("t");
    }


    //return teams by name ...
    /**
     * @param string $word
     * @return array
     */
    public function getTeamsByFirstLetters($word){
        $query = $this->getQueryBulder();
        if(!empty($word)) {
            $query
                ->select('t')->
                where(
                    $query->expr()->like('t.name', ':name')
                )->andWhere('t.confirmed=true')
                ->orderBy('t.name', 'ASC')
                ->setParameter('name', $word.'%');
        }else{
            $query
                ->select('t')
                ->Where('t.confirmed=true')
                ->orderBy('t.name', 'ASC');
        }
        return $query->getQuery()->getResult();
    }



}
