showAllTeams:
    path: /user/team/showAll
    defaults: {_controller: pitaksTeamBundle:Team:TeamsView}
oneTeam:
    path: /user/team/review/{teamId}
    defaults: {_controller: pitaksTeamBundle:Team:OneTeamView}
createTeam:
    path: /user/team/createTeam/{userId}
    defaults: {_controller: pitaksTeamBundle:Team:newTeam}
#user's teams
showUserTeam:
    path: /user/team/showMyTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUserTeams}
#invite to the team
showInvitedTeams:
    path: /user/team/showInvitedTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUsersInvitedTeams}
#user suggest team
showSuggestedTeams:
    path: /user/team/showSuggestedTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUsersSuggestedTeams}
deleteTeam:
    path: /user/team/{teamId}/delete
    defaults: {_controller: pitaksTeamBundle:Team:deleteTeam}
acceptTeam:
    path: /user/team/{teamId}/accept
    defaults: {_controller: pitaksTeamBundle:Team:acceptTeam}



