showAllTeams:
    path: /user/team/showAll
    defaults: {_controller: pitaksTeamBundle:Team:TeamsView}
oneTeam:
    path: /user/team/review/{teamId}
    defaults: {_controller: pitaksTeamBundle:Team:OneTeamView}
createTeam:
    path: /user/team/createTeam/{userId}
    defaults: {_controller: pitaksTeamBundle:Team:newTeam}
#user's teams
showUserTeam:
    path: /user/team/showMyTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUserTeams}
#invite to the team
showInvitedTeams:
    path: /user/team/showInvitedTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUsersInvitedTeams}
#user suggest team
showSuggestedTeams:
    path: /user/team/showSuggestedTeams
    defaults: {_controller: pitaksTeamBundle:Team:showUsersSuggestedTeams}
deleteTeam:
    path: /user/team/{teamId}/delete
    defaults: {_controller: pitaksTeamBundle:Team:deleteTeam}
acceptTeam:
    path: /user/team/{teamId}/accept
    defaults: {_controller: pitaksTeamBundle:Team:acceptTeam}
#team menu rautings....

teamMenu:
    path: /user/teamMenu/{teamId}
    defaults: {_controller: pitaksTeamBundle:Team:TeamMenu}
teamEachTableStat:
    path: /user/teamMenu/{teamId}/eachStat
    defaults: {_controller: pitaksTeamBundle:TeamStats:showEachStatsForTable}
#bendra statistika
commonTeamStat:
    path: /user/teamMenu/{teamId}/stats
    defaults: {_controller: pitaksTeamBundle:TeamStats:showAllTeamStatistic}


#teams search
teamSearchForm:
    path: user/searchTeams
    defaults: {_controller: pitaksTeamBundle:Team:teamSearchView}


teamSearchResults:
    path: user/searchTeamsResults
    defaults: {_controller: pitaksTeamBundle:Team:teamListsBySearch}

teamsNames:
    path: user/teamsNames
    defaults: {_controller: pitaksTeamBundle:Team:teamsNamesList}

#challengess

challengeTeam:
    path: user/teamMenu/{teamId}/challene/{anotherTeamId}
    defaults: {_controller: pitaksTeamBundle:TeamChallenge:ChallengePage}
saveTeamChallenge:
    path: user/teamMenu/{teamId}/challene/{anotherTeamId}/save
    defaults: {_controller: pitaksTeamBundle:TeamChallenge:saveChallenge}