services:
     team_service:
              class: pitaks\TeamBundle\Services\TeamService
              arguments: ["@doctrine.orm.entity_manager"]
              calls:
                      - [setContainer, ['@service_container']]
