adminView:
    path: admin/
    defaults: {_controller: UserBundle:Admin:index}
show_users:
    path: /allUsers
    defaults: {_controller: UserBundle:User:showUsers}
getUsersName:
    path: /usersList
    defaults: {_controller: UserBundle:User:autocompleteUserNames}
userslist:
    path: /usersTableList
    defaults: {_controller: UserBundle:User:userList}
userReservationList:
    path: /UserReservationsList
    defaults: {_controller: UserBundle:Profile:userRegisteredReservations}
userDeleteRegisteredReservation:
    path: /UserDeleteRegisteredReservation
    defaults: {_controller: UserBundle:Profile:deleteUserReservation}
userUnconfirmedReservationList:
    path: /userUnconfirmedReservationList
    defaults: {_controller: UserBundle:Profile:userUnconfirmedRegisteredReservations}
userConfirmRegisteredReservation:
    path: /userConfirmRegisteredReservation
    defaults: {_controller: UserBundle:Profile:acceptUserReservation}

#challenges
userChallengeMain:
    path: /challenge/{username}
    defaults: {_controller: UserBundle:Challenge:ChallengePage}

userChallengeSave:
     path: /challenge/{username}/save
     defaults: {_controller: UserBundle:Challenge:saveChallenge}
#UserStats
userStat:
    path: /user/stats/{username}
    defaults: {_controller: UserBundle:UserStatistic:showAllLoginUserStatistic}
myUserStat:
    path: /user/stats
    defaults: {_controller: UserBundle:UserStatistic:myStats}
#last user games
lastUserGames:
    path: /user/lastGames
    defaults: {_controller: UserBundle:UserStatistic:lastTenUserGames}
#user table rating
userTableRates:
    path: /user/tableRatings
    defaults: {_controller: UserBundle:User:userTableRatesList}
userImageUnpload:
    path: /user/image
    defaults: {_controller: UserBundle:Image:upload}
userImageDelete:
    path: /user/image/delete
    defaults: {_controller: UserBundle:Image:delete}