services:
    acme_user.registration.form.type:
        class: pitaks\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pitaks_user_registration }
    user_statistic_service:
         class: pitaks\UserBundle\Services\UserStatisticService
         arguments: ["@doctrine.orm.entity_manager"]
         calls:
                 - [setContainer, ['@service_container']]
    user_lastviews_service:
             class: pitaks\UserBundle\Services\LastReviewsService
             arguments: ["@doctrine.orm.entity_manager"]
             calls:
                     - [setContainer, ['@service_container']]

    user.after_registration.listener:
        class: pitaks\UserBundle\EventListener\AfterUserRegistrationListener
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
        tags:
            -  { name: kernel.event_listener, event: fos_user.registration.completed, method: onUserRegistered }
